spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minesite
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    generate-ddl: true

